name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=20.3.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.5
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - torchvision=0.12.0
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==0.4.3
    - altair==4.2.0
    - antlr4-python3-runtime==4.8
    - anyio==3.6.1
    - asgiref==3.5.2
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - blinker==1.5
    - cachetools==5.2.0
    - click==8.1.3
    - coloredlogs==15.0.1
    - commonmark==0.9.1
    - debugpy==1.6.3
    - decorator==5.1.1
    - diffusers==0.2.4
    - dnspython==2.2.1
    - einops==0.3.0
    - email-validator==1.2.1
    - entrypoints==0.4
    - executing==0.10.0
    - fastapi==0.81.0
    - filelock==3.8.0
    - flatbuffers==2.0
    - frozenlist==1.3.1
    - fsspec==2022.7.1
    - ftfy==6.1.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - h11==0.13.0
    - httptools==0.4.0
    - huggingface-hub==0.8.1
    - humanfriendly==10.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - imgaug==0.2.6
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - invisible-watermark==0.1.5
    - ipykernel==6.15.1
    - ipython==8.4.0
    - ipywidgets==8.0.1
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.14.0
    - jupyter-client==7.3.4
    - jupyter-core==4.11.1
    - jupyterlab-widgets==3.0.2
    - kornia==0.6.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - mpmath==1.2.1
    - multidict==6.0.2
    - nest-asyncio==1.5.5
    - networkx==2.8.6
    - numpy==1.23.2
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - onnx==1.12.0
    - onnxruntime==1.12.1
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.6.0.66
    - orjson==3.8.0
    - packaging==21.3
    - pandas==1.4.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pudb==2019.2
    - pure-eval==0.2.2
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.2
    - pydeck==0.7.1
    - pydeprecate==0.3.1
    - pygments==2.13.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - python-multipart==0.0.5
    - pytorch-lightning==1.4.2
    - pytz==2022.2.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==23.2.1
    - regex==2022.8.17
    - requests-oauthlib==1.3.1
    - rich==12.5.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.0
    - semver==2.13.0
    - smmap==5.0.0
    - sniffio==1.2.0
    - stack-data==0.4.0
    - starlette==0.19.1
    - streamlit==1.12.0
    - sympy==1.10.1
    - tabulate==0.8.10
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - test-tube==0.7.5
    - tifffile==2022.8.12
    - tokenizers==0.12.1
    - toml==0.10.2
    - toolz==0.12.0
    - torch-fidelity==0.3.0
    - torchmetrics==0.6.0
    - tornado==6.2
    - tqdm==4.64.0
    - traitlets==5.3.0
    - transformers==4.21.1
    - tzdata==2022.2
    - tzlocal==4.2
    - ujson==5.4.0
    - urwid==2.1.2
    - uvicorn==0.17.6
    - uvloop==0.16.0
    - validators==0.20.0
    - watchdog==2.1.9
    - watchgod==0.8.2
    - wcwidth==0.2.5
    - websockets==10.3
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.2
    - yarl==1.8.1
    - zipp==3.8.1
